# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0015_maprenderingjob_poi_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprenderingjob',
            name='submitterip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
