# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0016_submitterip_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='upload/general/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('gpx', 'GPX Track'), ('umap', 'UMAP Export File'), ('poi', 'POI File')], max_length=4)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maposmatic.MapRenderingJob')),
            ],
        ),
    ]
