# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0017_uploadfile'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO maposmatic_uploadfile (uploaded_file, file_type, job_id) SELECT track as uploaded_file, 'gpx' as file_type, id as job_id FROM maposmatic_maprenderingjob WHERE LENGTH(track) > 0", 
        ),
        migrations.RunSQL(
            "INSERT INTO maposmatic_uploadfile (uploaded_file, file_type, job_id) SELECT umap as uploaded_file, 'umap' as file_type, id as job_id FROM maposmatic_maprenderingjob WHERE LENGTH(umap) > 0", 
        ),
        migrations.RunSQL(
            "INSERT INTO maposmatic_uploadfile (uploaded_file, file_type, job_id) SELECT poi_file as uploaded_file, 'poi' as file_type, id as job_id FROM maposmatic_maprenderingjob WHERE LENGTH(poi_file) > 0", 
        ),
    ]
