# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-11 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0018_allow_empty_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprenderingjob',
            name='renderstep',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
